### ISSUE TITLE
'Resource Manager' link returns 404

### ISSUE THREAD

**Issue by ChrisTheBaron** [UniversityRadioYork/MyRadio#555] opened 2016-05-02 18:46 UTC
https://ury.org.uk/myradio/Resource/ is non-existent

**Comment by LloydW93** [comment] 2016-05-03 09:29
This was never implemented, but the link is only exposed to the computing team.

**Comment by LloydW93** [comment] 2016-05-03 09:30
Duplicate of #352

**Closed by LloydW93** 2016-05-03 09:30 UTC
