### ISSUE TITLE
Playlist track search - song can't be found due to limit in dropdown

### ISSUE THREAD

**Issue by AJDurant** [UniversityRadioYork/MyRadio#375] opened 2015-02-23 18:24 UTC
eg Sing - Ed Sheeran

**Comment by Eiron** [comment] 2015-03-19 03:28
I would actually prefer a playlist editing system more akin to the way the Show Planner works now. It would be extremely unusual for one to be unable to find a song using that.

**Comment by Eiron** [comment] 2015-05-17 01:17
This problem is still not fixed, e.g. Believe - Mumford & Sons.

**Comment by LloydW93** [comment] 2015-05-17 09:44
The problem is fixed in the code base. Whether or not it has been put live on a server is not a bug.

**Comment by LloydW93** [comment] 2015-05-17 09:50
I just searched for "Believe" and the song appeared in the dropdown.

**Comment by adfw** [comment] 2015-05-17 09:51
Note that it's currently case-sensitive

**Comment by adfw** [comment] 2015-05-17 10:12
Hopefully a bit better now thanks to #443

**Comment by Eiron** [comment] 2015-05-17 18:19
e.g. i - Kendrick Lamar, which previously you might have been able to find by searching for the artist instead of the song title in the 'title' box.

**Closed** 2015-05-17 18:21 UTC

**Comment by LloydW93** [comment] 2015-05-17 18:28
Creating new issues to track problems created by #441 - #445 and #446
