### ISSUE TITLE
Explicit button on Track Uploader does nothing?

### ISSUE THREAD

**Issue by Eiron** [UniversityRadioYork/MyRadio#448] opened 2015-05-19 23:12 UTC
Least, those tracks I have checked as explicit are coming through as 'u'. One even upgraded itself to a 'y'. It was definitely not a 'y'.

**Comment by AJDurant** [comment] 2015-05-19 23:16
code looks correct, will test when time

**Comment by LloydW93** [comment] 2015-05-19 23:22
https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Classes/Daemons/MyRadio_ExplicitDaemon.php#L43

May be part of the problem - things may be initially getting marked as unknown for some reason then this comes along and makes its guess, OR, findByOptions' clean filter is broken.

**Comment by adfw** [comment] 2015-05-19 23:26
https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Controllers/NIPSWeb/confirm_central_upload.php#L17 could be the culprit - if it's not set, then it becomes NULL. Meaning https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Classes/ServiceAPI/MyRadio_Track.php#L662 never becomes true. Although this is about Explicit going 'u' as well, could be something to check.

**Comment by AJDurant** [comment] 2015-05-19 23:34
@adfw that is the intended behavior, the explicit tick should only set explicit, not clean. So it will set explicit, or it will send null and be unknown. But the functionality is there in track creation so other methods can set tracks to be clean. See the discussion on #326

**Comment by adfw** [comment] 2015-05-19 23:35
Should be a code comment there then about the (current) dead code

**Comment by AJDurant** [comment] 2015-05-19 23:36
It's not dead code, and it's pretty obvious

**Comment by adfw** [comment] 2015-05-19 23:39
I've just shown that it's not clear that the fact it will *never* set clean to true, even though the code to set it true is present. Needs a note saying that the check for explicit === false is for future enhancements.

**Comment by AJDurant** [comment] 2015-05-19 23:50
That function *will* set clean to 'y' if it is asked to do so. That is not dead code.
The fact that the user-side functionality won't ask it to should not be documented in this function, as it has no relevance there. Perhaps on the user side.

**Comment by adfw** [comment] 2015-05-19 23:51
So documentation on the isset at https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Controllers/NIPSWeb/confirm_central_upload.php#L17 then, since that prevents a 'y' getting set.

**Comment by Eiron** [comment] 2015-05-20 01:10
Could it not just definitely set it to 'n'? If somebody has checked that box I feel it should override whatever the search function thinks, especially considering jukebox will play songs marked 'u' (which is ideal, because going through and fixing everything by hand would be a huge task), and these songs do not give a warning when selected in Show Planner.

**Comment by AJDurant** [comment] 2015-05-20 01:12
Ticking the box should set it to 'n', that is what the code does, and what
I said before. I will test properly to confirm when I have time.

**Comment by AJDurant** [comment] 2016-11-07 19:44
#591 might help with this

**Comment by AJDurant** [comment] 2016-11-07 19:52
Heh, I have seen the problem, the form submission never sends that input.

See: https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Public/js/nipsweb.managelibrary.js#L60-L220

**Closed** 2017-01-07 21:48 UTC
Labels: bug
